name: runmodel-environment-mrl-amis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=2.1.1
  - pandas=2.2.3
  - openpyxl=3.1.5
  - scikit-learn=1.5.2
  - matplotlib=3.9.2
  - pygmo=2.19.7
  - seaborn=0.12.2
  - folium=0.14.0
  - polyline=1.4.0
  - grpcio=1.74.1
  - grpcio-tools=1.74.1
  - protobuf=6.31.1
  - loguru>=0.6.0
  - pip
  - pip:
    - -e .